#' BUGSnet: Bayesian network meta-analyses in compliance with best practice guidelines.
#'
#' BUGSnet (NETwork meta-analysis with BUGS) is a feature-rich R package to conduct Bayesian network meta-analyses in compliance with best practice guidelines and facilitate reporting. 
#' Bayesian analyses are conducted with JAGS and BUGS code is automatically generated by the package based on the user's inputs. 
#' Outputs include network plots, tables of network characteristics, league tables and league heat plots, SUCRA plots, rankograms, forest plots, leverage plots, traceplots, posterior mean deviance comparison plots.
#' 
#' To be able to use this package, you must have installed JAGS (Just Another Gibbs Sampler) on your computer.
#' 
#' BUGSnet is not distributed on CRAN but rather in the form of a .tar.gz source file. To install BUGSnet, run
#' 
#' install.packages("path/BUGSnet_0.0.0.9000.tar.gz", repos = NULL, type = "source")
#'
#' where "path/BUGSnet_0.0.0.9000.tar.gz" should be replaced to reflect the location of the .tar.gz file on your computer.
#' 
#' @name BUGSnet
#' @docType package
#' 
#' @references
#' \insertRef{JAGSmanual}{BUGSnet}
#' 
#' \insertRef{JAGSweb}{BUGSnet}
#' 
#' @importFrom stats density median offset update
#' @import ggplot2
#' @importFrom igraph incident is.connected clusters V E graph_from_data_frame layout_in_circle ecount vcount
#' @import rjags
#' @import extrafont
#' @import meta
#' @import purrr
#' @importFrom scales pretty_breaks
#' @importFrom rlang quo
#' @importFrom tibble tibble
#' @importFrom plyr mapvalues
#' @importFrom utils combn globalVariables
#' @import tidyr
#' @importFrom graphics lines par plot points text
#' @importFrom magrittr %>% %<>%
#' @import dplyr
#' @importFrom Rdpack reprompt 
#' @importFrom grDevices colorRampPalette
#' @importFrom RColorBrewer brewer.pal brewer.pal.info

if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))
