#' BUGSnet: Bayesian network meta-analysis in compliance with best practice guidelines.
#'
#' BUGSnet (Bayesian inference Using Gibbs Sampling to conduct NETwork meta-analysis) is a feature-rich R package to conduct Bayesian network meta-analyses in compliance with best practice and reporting guidelines. 
#' Bayesian analyses are conducted with JAGS and BUGS code is automatically generated by the package based on the user's inputs. 
#' Outputs are highly customizable and include network plots, tables of network characteristics, league tables and league heat plots, SUCRA plots, rankograms, forest plots, leverage plots, traceplots, posterior mean deviance comparison plots.
#' 
#' To be able to use this package, you must have installed JAGS (Just Another Gibbs Sampler) on your computer.
#' 
#' How to cite this work? Type citation("BUGSnet").
#' 
#' @name BUGSnet
#' @docType package
#' 
#' @references
#' \insertRef{JAGSmanual}{BUGSnet}
#' 
#' \insertRef{JAGSweb}{BUGSnet}
#' 
#' @importFrom stats density median offset update qnorm
#' @import ggplot2
#' @importFrom igraph incident is.connected clusters V E graph_from_data_frame ecount vcount layout_as_bipartite layout_as_star layout_as_tree layout_in_circle layout_nicely layout_on_grid layout_on_sphere layout_randomly layout_with_dh layout_with_fr layout_with_gem layout_with_graphopt layout_with_kk layout_with_lgl layout_with_mds layout_with_sugiyama
#' @import rjags
#' @import extrafont
#' @import meta
#' @import purrr
#' @importFrom scales pretty_breaks rescale
#' @importFrom rlang quo
#' @import tibble 
#' @importFrom plyr mapvalues
#' @importFrom utils combn globalVariables data
#' @import tidyr
#' @importFrom graphics lines par plot points text
#' @importFrom magrittr %>% %<>%
#' @import dplyr
#' @importFrom Rdpack reprompt 
#' @importFrom stringr str_detect
#' @importFrom grDevices colorRampPalette dev.off
#' @importFrom RColorBrewer brewer.pal brewer.pal.info

if(getRversion() >= "2.15.1")  utils::globalVariables(c(".", ":="))
